additional_menus_for_route_edit
Puzzle-f/WorkSchedule pull request #16
Opened 2022-05-02 19:29 UTC by saityan

2022-05-02 20:11 UTC, S1aks requested changes

2022-05-02 20:11 UTC, S1aks commented on app/src/main/java/com/example/workschedule/MainActivity.kt
> +                R.id.drivers_list,
Надо еще поправить id. Чтобы легко было искать этот id при написании, думаю нужно префикс nav_ добавить(к примеру nav_drivers). Чтобы понятно было, что этот id относится к навигации приложения.

2022-05-02 20:11 UTC, S1aks commented on app/src/main/java/com/example/workschedule/ui/driver_edit/DriverEditFragment.kt
> +            ViewModelProvider(this)[DriverEditViewModel::class.java]
Ну этот фрагмент наверное не брал никто еще... Поэтому через провайдер, а не через койн

2022-05-02 20:11 UTC, S1aks commented on app/src/main/java/com/example/workschedule/ui/route_edit/DateTimePickerFragment.kt
> +        datetimePickerViewModel =
можно инжектить через койн, прописав в modules.kt

2022-05-02 20:11 UTC, S1aks commented on app/src/main/java/com/example/workschedule/ui/route_edit/RouteEditFragment.kt
> +        routeEditViewModel =
думаю тоже через койн сделать надо

2022-05-02 20:11 UTC, S1aks commented on app/src/main/res/layout/fragment_route_edit.xml
> +    <androidx.recyclerview.widget.RecyclerView
Пока не понял зачем столько Ресайклеров... надо разобраться

2022-05-02 20:18 UTC, saityan commented on app/src/main/res/layout/fragment_route_edit.xml
> +    <androidx.recyclerview.widget.RecyclerView
На каждый список свой recycler. Можно и одним обойтись, но придется ему менять TopToBottom каждый раз, очищать и т.д. В данной реализации больше кода в макете, но должно быть меньше во фрагменте, памяти они все равно не жрут.

2022-05-03 12:23 UTC, kosykt approved these changes
Все хорошо

2022-05-03 17:37 UTC, S1aks approved these changes

2022-05-05 03:41 UTC, merged