Edit MainFragment adapter/viewmodel/usecases for output drivers names…
Puzzle-f/WorkSchedule pull request #19
Opened 2022-05-09 07:41 UTC by S1aks

Переделана сущность выезда поезда для отображения нужных данных в Главном окне (расписание поездов или список выездов), изменены сопутствующие классы. Весь хардкод вынесен в класс FakeData.kt, чтобы не искать его по всем папкам и файлам в последствии.
Главное окно теперь задействует алгоритм и происходит заполнение списка выездов машинистами.

2022-05-09 15:48 UTC, saityan requested changes

2022-05-09 15:48 UTC, saityan commented on app/src/main/java/com/example/workschedule/domain/FakeData.kt
> +val driverList = listOf(
При отображении списка машинистов путаются местами имя и фамилия. Надо поменять местами поля класса Driver, чтобы сначала шла фамилия, потом имя, потом отчество (если есть).

2022-05-09 15:48 UTC, saityan commented on app/src/main/java/com/example/workschedule/di/modules.kt
>      single { get<DriverDataBase>().trainDao() }
Я бы удалил закоменченный код выше (строки 19-23), он вводит в замешательство.

2022-05-09 15:48 UTC, saityan commented on app/src/main/java/com/example/workschedule/domain/models/TrainRun.kt
> +    val trainDirection: String,
А нам пункт отправления точно не нужен, достаточно только пункта назначения?

2022-05-09 15:48 UTC, saityan commented on app/src/main/java/com/example/workschedule/ui/main/MainFragmentAdapter.kt
> +                trainRun.startTime.format(DateTimeFormatter.ofPattern("d.MM.y"))
А есть вариант добавлять нолик перед датой и/или временем отправления, если любая из них меньше десяти? В правом столбце не обязательно, в левом мне кажется так будет нагляднее.

2022-05-09 15:48 UTC, saityan commented on app/src/main/java/com/example/workschedule/ui/main/MainFragmentViewModel.kt
> +    //    val trains: StateFlow<List<TrainRun>> = flow {
имхо закоменченный код оставлять не надо, он создает путаницу, меня учили что так стоит делать только в самом крайнем случае.

2022-05-09 16:59 UTC, kosykt requested changes
Согласен со всем, что написал Валерич

2022-05-09 17:45 UTC, S1aks commented on app/src/main/java/com/example/workschedule/domain/models/TrainRun.kt
> +    val trainDirection: String,
по ТЗ пункт отправления отсутствует. Он для основной работы не нужен. для всей программы он один. Можно будет в последствии ввести это поле для информации.

2022-05-10 11:50 UTC, saityan approved these changes

2022-05-10 13:02 UTC, merged